// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: dummy.sql

package gensql

import (
	"context"
	"encoding/json"
)

const insertData = `-- name: InsertData :one
INSERT INTO dummy (
    "data"
) VALUES (
    $1
)
RETURNING id, data
`

func (q *Queries) InsertData(ctx context.Context, data json.RawMessage) (Dummy, error) {
	row := q.db.QueryRowContext(ctx, insertData, data)
	var i Dummy
	err := row.Scan(&i.ID, &i.Data)
	return i, err
}
