// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package gensql

import (
	"context"
	"encoding/json"
)

type Querier interface {
	InsertData(ctx context.Context, data json.RawMessage) (Dummy, error)
}

var _ Querier = (*Queries)(nil)
