kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: nada-db-testa
  namespace: nada
  labels:
    team: nada
spec:
  image: ghcr.io/navikt/nada-db-test:v8
  port: 8080
  replicas:
    min: 1
    max: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_12
        databases:
          - name: nada-db-test
