apiVersion: v1
kind: ServiceAccount
metadata:
  name: nada-db-test
  annotations:
    iam.gke.io/gcp-service-account: nada-db-test@knada-gcp.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nada-db-test
  namespace: knada-system
  labels:
    app: nada-db-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nada-db-test
  template:
    metadata:
      labels:
        app: nada-db-test
    spec:
      serviceAccountName: nada-db-test
      imagePullSecrets:
      - name: ghcr-credentials
      containers:
      - name: nada-db-test
        image: ghcr.io/navikt/nada-db-test:v8
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: nada-db-test
      - name: cloudsql-proxy
        command:
        - /cloud-sql-proxy
        - --max-sigterm-delay=30s
        - --address=0.0.0.0
        - --port=5432
        - knada-gcp:europe-west1:nada-db-test
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0-alpine
        ports:
        - containerPort: 5432
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsGroup: 2
          runAsNonRoot: true
          runAsUser: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
